### ISSUE TITLE
issue with zero value and non-96 mutation categories

### ISSUE THREAD

**Issue by blsfoxfox** [rvalieris/signeR#12]
Hi,

I have a matrix with 136 samples x 112 snv categories. Sample 20 has no snv at all, but after running signeR with 3 signatures, the mutation exposure (Ehat) of sample 20 is not zero.

1. Could I run signeR on any number of snv categories other than 96?
2. Should mutation exposure of previous example be zero?

The matrix is attached.
[example_112snv_matrix.xlsx](https://github.com/rvalieris/signeR/files/3129005/example_112snv_matrix.xlsx)

Thanks,
LS

**Comment by rvalieris** [comment]
Hello,

1. yes, signeR can be run with any number of categories, however the plots are made for the 96 triplets:change configuration, so you will need to make custom plots for it.

2. samples without any counts on the matrix are usually removed before the analysis. because its not possible to infer the presence of any signature in this sample.
the exposure of a sample without a signature will have really small numbers but it won't be zero, this is due to the way the method works and its expected. exposure is relative to the samples/dataset used.
